name: GPT Commits summarizer

on:
  pull_request_target:
    types: [ opened, synchronize ]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: KanHarI/gpt-commit-summarizer@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
